// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/port-domain-svc.proto

package portdomainsvc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Port struct {
	PortCode             string   `protobuf:"bytes,1,opt,name=portCode,proto3" json:"portCode,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Latitude             string   `protobuf:"bytes,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Province             string   `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	Timezone             string   `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Code                 string   `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_126c27d9abff26f7, []int{0}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetPortCode() string {
	if m != nil {
		return m.PortCode
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Port) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *Port) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *Port) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Port) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Port) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AddPortsReq struct {
	Ports                []*Port  `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPortsReq) Reset()         { *m = AddPortsReq{} }
func (m *AddPortsReq) String() string { return proto.CompactTextString(m) }
func (*AddPortsReq) ProtoMessage()    {}
func (*AddPortsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_126c27d9abff26f7, []int{1}
}

func (m *AddPortsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPortsReq.Unmarshal(m, b)
}
func (m *AddPortsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPortsReq.Marshal(b, m, deterministic)
}
func (m *AddPortsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPortsReq.Merge(m, src)
}
func (m *AddPortsReq) XXX_Size() int {
	return xxx_messageInfo_AddPortsReq.Size(m)
}
func (m *AddPortsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPortsReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddPortsReq proto.InternalMessageInfo

func (m *AddPortsReq) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_126c27d9abff26f7, []int{2}
}

func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (m *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(m, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Port)(nil), "portdomainsvc.Port")
	proto.RegisterType((*AddPortsReq)(nil), "portdomainsvc.AddPortsReq")
	proto.RegisterType((*EmptyReply)(nil), "portdomainsvc.EmptyReply")
}

func init() { proto.RegisterFile("proto/port-domain-svc.proto", fileDescriptor_126c27d9abff26f7) }

var fileDescriptor_126c27d9abff26f7 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x31, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0x95, 0x7f, 0xd3, 0xfe, 0xd3, 0x2b, 0x0c, 0x98, 0xc5, 0x04, 0x86, 0x2a, 0x53, 0x19,
	0x1a, 0xa4, 0xb2, 0xb0, 0x56, 0xc0, 0x8e, 0x82, 0xc4, 0x1e, 0xe2, 0x13, 0xb2, 0x94, 0xf8, 0x82,
	0x63, 0x22, 0x85, 0x4f, 0xc9, 0x47, 0x42, 0x67, 0x27, 0x14, 0xba, 0xdd, 0x7b, 0xbf, 0xd3, 0xbb,
	0x3b, 0x1b, 0x2e, 0x5b, 0x4b, 0x8e, 0x6e, 0x5a, 0xb2, 0x6e, 0xab, 0xa8, 0x29, 0xb5, 0xd9, 0x76,
	0x7d, 0x95, 0x7b, 0x57, 0x9c, 0xb2, 0x1d, 0xdc, 0xae, 0xaf, 0xb2, 0xaf, 0x08, 0xe2, 0x27, 0xb2,
	0x4e, 0xa4, 0x90, 0x30, 0xb9, 0x27, 0x85, 0x32, 0x5a, 0x47, 0x9b, 0x65, 0xf1, 0xa3, 0x85, 0x80,
	0xd8, 0x94, 0x0d, 0xca, 0x7f, 0xde, 0xf7, 0x35, 0x7b, 0x95, 0x76, 0x83, 0x9c, 0x05, 0x8f, 0x6b,
	0xce, 0xa8, 0x4b, 0xa7, 0xdd, 0x87, 0x42, 0x19, 0x87, 0x8c, 0x49, 0x8b, 0x2b, 0x58, 0xd6, 0x64,
	0xde, 0x02, 0x9c, 0x7b, 0x78, 0x30, 0xfc, 0x74, 0x4b, 0xbd, 0x36, 0x15, 0xca, 0xc5, 0x38, 0x7d,
	0xd4, 0xcc, 0x9c, 0x6e, 0xf0, 0x93, 0x0c, 0xca, 0xff, 0x81, 0x4d, 0xda, 0x6f, 0xc1, 0x1b, 0x27,
	0xe3, 0x16, 0xa4, 0x30, 0xbb, 0x83, 0xd5, 0x5e, 0x29, 0x3e, 0xaa, 0x2b, 0xf0, 0x5d, 0x5c, 0xc3,
	0x9c, 0x0f, 0xe9, 0x64, 0xb4, 0x9e, 0x6d, 0x56, 0xbb, 0xf3, 0xfc, 0xcf, 0x03, 0xe4, 0xdc, 0x57,
	0x84, 0x8e, 0xec, 0x04, 0xe0, 0xb1, 0x69, 0xdd, 0x50, 0x60, 0x5b, 0x0f, 0xbb, 0x17, 0x38, 0x63,
	0xf8, 0xe0, 0x5b, 0x9f, 0xd1, 0xf6, 0xba, 0x42, 0xb1, 0x87, 0x64, 0x0a, 0x17, 0xe9, 0x51, 0xd4,
	0xaf, 0xa9, 0xe9, 0xc5, 0x11, 0x3b, 0xe4, 0xbe, 0x2e, 0xfc, 0x47, 0xdc, 0x7e, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x84, 0x53, 0xcb, 0xda, 0xa7, 0x01, 0x00, 0x00,
}
