// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/port-domain-svc.proto

package portdomainsvc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddPortReq struct {
	PortCode             string   `protobuf:"bytes,1,opt,name=portCode,proto3" json:"portCode,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Latitude             string   `protobuf:"bytes,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Province             string   `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	Timezone             string   `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Code                 string   `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPortReq) Reset()         { *m = AddPortReq{} }
func (m *AddPortReq) String() string { return proto.CompactTextString(m) }
func (*AddPortReq) ProtoMessage()    {}
func (*AddPortReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_126c27d9abff26f7, []int{0}
}

func (m *AddPortReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPortReq.Unmarshal(m, b)
}
func (m *AddPortReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPortReq.Marshal(b, m, deterministic)
}
func (m *AddPortReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPortReq.Merge(m, src)
}
func (m *AddPortReq) XXX_Size() int {
	return xxx_messageInfo_AddPortReq.Size(m)
}
func (m *AddPortReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPortReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddPortReq proto.InternalMessageInfo

func (m *AddPortReq) GetPortCode() string {
	if m != nil {
		return m.PortCode
	}
	return ""
}

func (m *AddPortReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddPortReq) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AddPortReq) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *AddPortReq) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *AddPortReq) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *AddPortReq) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *AddPortReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_126c27d9abff26f7, []int{1}
}

func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (m *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(m, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddPortReq)(nil), "portdomainsvc.AddPortReq")
	proto.RegisterType((*EmptyReply)(nil), "portdomainsvc.EmptyReply")
}

func init() { proto.RegisterFile("proto/port-domain-svc.proto", fileDescriptor_126c27d9abff26f7) }

var fileDescriptor_126c27d9abff26f7 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4b, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0x89, 0x8e, 0xf3, 0x28, 0x74, 0x61, 0xaf, 0xda, 0xd1, 0x85, 0xcc, 0xca, 0xcd, 0x44,
	0xd0, 0x03, 0x88, 0xa8, 0x7b, 0x89, 0x5e, 0x20, 0x76, 0x17, 0xd2, 0x90, 0x74, 0xc5, 0x9e, 0x32,
	0x10, 0x0f, 0xea, 0x79, 0xa4, 0xaa, 0x33, 0x06, 0xdd, 0xd5, 0xff, 0x7d, 0x50, 0x2f, 0x38, 0xef,
	0x12, 0x31, 0x5d, 0x77, 0x94, 0x78, 0xeb, 0xa9, 0xad, 0x43, 0xdc, 0xee, 0x7a, 0x57, 0x2a, 0x35,
	0x27, 0x82, 0x33, 0xdd, 0xf5, 0x6e, 0xf3, 0x5d, 0x00, 0xdc, 0x7b, 0xff, 0x4c, 0x89, 0x2b, 0xfc,
	0x30, 0x6b, 0x58, 0x8a, 0x7f, 0x20, 0x8f, 0xb6, 0xb8, 0x2c, 0xae, 0x56, 0xd5, 0x6f, 0x36, 0x06,
	0x66, 0xb1, 0x6e, 0xd1, 0x1e, 0x28, 0xd7, 0x5a, 0x98, 0x0b, 0x3c, 0xd8, 0xc3, 0xcc, 0xa4, 0x96,
	0x1e, 0x4d, 0xcd, 0x81, 0x3f, 0x3d, 0xda, 0x59, 0xee, 0xb1, 0xcf, 0xe6, 0x02, 0x56, 0x0d, 0xc5,
	0xf7, 0x2c, 0x8f, 0x54, 0x4e, 0x40, 0xa7, 0x27, 0xea, 0x43, 0x74, 0x68, 0xe7, 0xe3, 0xf4, 0x31,
	0x8b, 0xe3, 0xd0, 0xe2, 0x17, 0x45, 0xb4, 0x8b, 0xec, 0xf6, 0x59, 0xb7, 0x90, 0x8d, 0x97, 0xe3,
	0x16, 0xe4, 0x71, 0x73, 0x0c, 0xf0, 0xd4, 0x76, 0x3c, 0x54, 0xd8, 0x35, 0xc3, 0xcd, 0x2b, 0x9c,
	0xca, 0x89, 0x8f, 0x7a, 0xf7, 0x0b, 0xa6, 0x3e, 0x38, 0x34, 0x77, 0xb0, 0x18, 0x4f, 0x37, 0x67,
	0xe5, 0x9f, 0xb7, 0x94, 0xd3, 0x4b, 0xd6, 0xff, 0xd5, 0xd4, 0xf5, 0x6d, 0xae, 0x2f, 0xbd, 0xfd,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x72, 0xb7, 0x8c, 0xf5, 0x71, 0x01, 0x00, 0x00,
}
